server:
  port: 9020
spring:
  application:
    name:  changel-blog
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true
swagger:
  base-package: com.changel.blog
  title: blog-doc
  version: 1.0
  description: 博客
  contact-name: changel
  contact-email: unsupport
  contact-url: https://github.com/changel/spring-cloud-changel
  group-name: spring-cloud-changel-blog