spring:
  application:
    name:  changel-blog


swagger:
  base-package: com.changel.blog
  title: blog-doc
  version: 1.0
  description: 网关接口
  contact-name: changel
  contact-email: unsupport
  contact-url: https://github.com/changel/spring-cloud-changel
  group-name: spring-cloud-changel-blog