server:
  port: 80
spring:
  application:
    name:  changel-gateway
  cloud:
    gateway:
      routes:
        - id: changel-major
          uri: "http://localhost:9000/"
          predicates:
            - Path=/frontend/api/major/**
        - id: changel-nacos
          uri: "http://localhost:9010/"
          predicates:
            - Path=/frontend/api/nacos/**
