server:
  port: 8080
spring:
  application:
    name:  changel-gateway
  cloud:
    gateway:
      routes:
        - id: changel-major
          uri: "http://localhost:9000/"
          predicates:
            - Path=/frontend/api/gateway/**
