server:
  port: 80
spring:
  application:
    name:  changel-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: changel-major
#          uri: "http://localhost:9000/"
          uri: lb://changel-major
          predicates:
            - Path=/api/major/**
        - id: changel-nacos
          uri: lb://changel-nacos
          predicates:
            - Path=/api/nacos/**
        - id: changel-blog
          uri: lb://changel-blog
          predicates:
            - Path=/api/blog/**